version: '3.1'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_USER: backend
      MYSQL_PASSWORD: notSecure
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
